## cat .codecov.yaml | curl --data-binary @- https://codecov.io/validate
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
