# manually check and fix the license declaration
#
# make check-license
# make format-license

headerPath = "hack/license-header.txt"

baseDir = "."

includes = [
    '*.go',
    'Makefile'
]

excludes = [
    '**/.git/**',
    'examples/**'
]

[git]
attrs = 'enable'
ignore = 'auto'

[properties]
copyrightOwner = "Greptime Team"
