# manually check and fix the license declaration
#
# make hawkeye
# make check-license
# make format-license

headerPath = "hack/license-header.txt"

baseDir = "."

includes = [
    '*.go',
    'Makefile'
]

[properties]
copyrightOwner = "Greptime Team"

[git]
attrs = 'enable'
ignore = 'auto'
