# manually check and fix the license declaration
#
# make hawkeye
# make check-lincense-header
# make format-lincense-header

headerPath = "LICENSE"

baseDir = "."

includes = [
    '*.go'
    #'*.yaml',
    #'Makefile',
    #'*.toml'
]

[properties]
inceptionYear = 2024
copyrightOwner = "Greptime Team"

[git]
attrs = 'enable'
ignore = 'auto'
