name: License Header Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches:
      - "main"

jobs:
  license-header-check:
    name: license-header-check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Check License Header
      shell: bash
      run: |
        make check-license
